### ISSUE TITLE
Noll ability 2C

### ISSUE THREAD

**Issue by kamiere** [cyigger/korby#1]
is broken

https://github.com/cyigger/korby/assets/136649510/c160cc7a-da78-4b2c-b8f6-9303296824a6

**Comment by kamiere** [comment]
so for some reason it only teleports when you dont have enough meter to do another 2c

**Comment by JonTheCopycat** [comment]
This issue was fixed by adding "ctrl = 0" to the statedef of the teleport. Issue fixed.
